// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDljiTbkMdxBC28J9sXilXoKXfW8kaAANA',
    appId: '1:558124852512:web:0137e21bbb17d3aa1ce345',
    messagingSenderId: '558124852512',
    projectId: 'agriconnect-180f1',
    authDomain: 'agriconnect-180f1.firebaseapp.com',
    storageBucket: 'agriconnect-180f1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAx41CMTm9HVoDrUcLPc7NonbeGQAbgW2w',
    appId: '1:558124852512:android:d55124e52e24c93f1ce345',
    messagingSenderId: '558124852512',
    projectId: 'agriconnect-180f1',
    storageBucket: 'agriconnect-180f1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwasA5nXRtiNXOPxJwQ4X7Dfw8QTgrUPk',
    appId: '1:558124852512:ios:4ba70f2d8d8dccfd1ce345',
    messagingSenderId: '558124852512',
    projectId: 'agriconnect-180f1',
    storageBucket: 'agriconnect-180f1.appspot.com',
    iosBundleId: 'com.example.agriTech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwasA5nXRtiNXOPxJwQ4X7Dfw8QTgrUPk',
    appId: '1:558124852512:ios:debab2244b04a9341ce345',
    messagingSenderId: '558124852512',
    projectId: 'agriconnect-180f1',
    storageBucket: 'agriconnect-180f1.appspot.com',
    iosBundleId: 'com.example.agriTech.RunnerTests',
  );
}
